"""sciso HTML report generator.

Generates a self-contained HTML report with interactive Plotly
visualizations. No dependency on ezcharts, dominate, or bokeh.
"""
import json
from pathlib import Path

import numpy as np
import pandas as pd

from ._logging import get_named_logger, wf_parser

REPORT_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>sciso Report</title>
<script src="https://cdn.plot.ly/plotly-2.27.0.min.js" charset="utf-8"></script>
<script>
// Fallback: if Plotly CDN fails, plots show "Plotly not loaded" instead of crashing
if (typeof Plotly === 'undefined') {{
    window.Plotly = {{ newPlot: function(id) {{
        document.getElementById(id).innerHTML = '<p style="color:#999">Interactive plot requires internet (Plotly CDN)</p>';
    }} }};
}}
</script>
<style>
body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI',
       Roboto, sans-serif; margin: 40px; background: #fafafa; }}
h1 {{ color: #1a1a2e; border-bottom: 3px solid #4361ee; padding-bottom: 10px; }}
h2 {{ color: #3a0ca3; margin-top: 40px; }}
h3 {{ color: #4361ee; }}
.section {{ background: white; padding: 24px; margin: 20px 0;
           border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }}
table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
th {{ background: #4361ee; color: white; padding: 10px 14px;
     text-align: left; font-size: 13px; }}
td {{ padding: 8px 14px; border-bottom: 1px solid #e0e0e0; font-size: 13px; }}
tr:hover {{ background: #f5f5f5; }}
.stat {{ display: inline-block; background: #e8eaf6; padding: 6px 14px;
        border-radius: 4px; margin: 4px; font-size: 13px; }}
.plot {{ margin: 16px 0; }}
p {{ color: #333; line-height: 1.6; }}
.badge {{ display: inline-block; padding: 3px 8px; border-radius: 12px;
          font-size: 11px; font-weight: bold; }}
.badge-novel {{ background: #ff6b6b; color: white; }}
.badge-known {{ background: #51cf66; color: white; }}
</style>
</head>
<body>
<h1>sciso Analysis Report</h1>
<p>Isoform-Resolved Inference for Single-cells</p>
{sections}
<footer style="margin-top:40px; color:#999; font-size:12px;">
Generated by sciso v0.1.0
</footer>
</body>
</html>"""


def argparser():
    """Create argument parser."""
    parser = wf_parser("report")

    parser.add_argument(
        "--out_dir", type=Path, required=True,
        help="sciso output directory (from sciso run).")
    parser.add_argument(
        "--output", type=Path, default="sciso_report.html",
        help="Output HTML report path.")

    return parser


def _table_html(df, max_rows=50):
    """Convert DataFrame to HTML table."""
    if len(df) == 0:
        return "<p>No data available.</p>"
    df = df.head(max_rows)
    header = "".join(f"<th>{c}</th>" for c in df.columns)
    rows = []
    for _, row in df.iterrows():
        cells = "".join(f"<td>{v}</td>" for v in row.values)
        rows.append(f"<tr>{cells}</tr>")
    return f"<table><thead><tr>{header}</tr></thead><tbody>{''.join(rows)}</tbody></table>"


def _scatter_plot_html(df, x, y, color=None, title="", div_id="plot"):
    """Generate Plotly scatter plot HTML."""
    traces = []
    if color and color in df.columns:
        for grp_name in sorted(df[color].unique()):
            sub = df[df[color] == grp_name]
            traces.append(f"""{{
                x: {sub[x].tolist()},
                y: {sub[y].tolist()},
                mode: 'markers',
                type: 'scatter',
                name: '{grp_name}',
                marker: {{size: 3, opacity: 0.6}}
            }}""")
    else:
        traces.append(f"""{{
            x: {df[x].tolist()},
            y: {df[y].tolist()},
            mode: 'markers',
            type: 'scatter',
            marker: {{size: 3, opacity: 0.6}}
        }}""")

    return f"""<div id="{div_id}" class="plot"></div>
<script>
Plotly.newPlot('{div_id}', [{','.join(traces)}], {{
    title: '{title}',
    xaxis: {{title: '{x}'}},
    yaxis: {{title: '{y}'}},
    showlegend: true,
    height: 500
}});
</script>"""


def _histogram_html(values, title="", xlabel="", div_id="hist"):
    """Generate Plotly histogram HTML."""
    return f"""<div id="{div_id}" class="plot"></div>
<script>
Plotly.newPlot('{div_id}', [{{
    x: {values.tolist()},
    type: 'histogram',
    nbinsx: 50,
    marker: {{color: '#4361ee', opacity: 0.7}}
}}], {{
    title: '{title}',
    xaxis: {{title: '{xlabel}'}},
    yaxis: {{title: 'Count'}},
    height: 400
}});
</script>"""


def _build_clustering_section(out_dir):
    """Build clustering section."""
    html = ""
    umap_file = out_dir / "joint.umap.tsv"
    if umap_file.exists():
        umap_df = pd.read_csv(umap_file, sep='\t')
        html += "<h2>Dual-Layer Clustering</h2>\n<div class='section'>\n"
        html += "<p>Cells clustered by gene expression and isoform "
        html += "usage patterns jointly.</p>\n"

        if 'D1' in umap_df.columns and 'cluster' in umap_df.columns:
            html += _scatter_plot_html(
                umap_df, 'D1', 'D2', color='cluster',
                title='Joint UMAP (Gene + Isoform)',
                div_id='joint_umap')

        n_cells = len(umap_df)
        n_clusters = umap_df['cluster'].nunique() \
            if 'cluster' in umap_df.columns else 0
        html += f"<span class='stat'>Cells: {n_cells}</span>\n"
        html += f"<span class='stat'>Clusters: {n_clusters}</span>\n"

        # Comparison stats
        comp_file = out_dir / "cluster_comparison.json"
        if comp_file.exists():
            with open(comp_file) as fh:
                comp = json.load(fh)
            ari = comp.get('ari', 'N/A')
            nmi = comp.get('nmi', 'N/A')
            if isinstance(ari, float):
                ari = f"{ari:.3f}"
            if isinstance(nmi, float):
                nmi = f"{nmi:.3f}"
            html += f"<span class='stat'>ARI (gene vs isoform): "
            html += f"{ari}</span>\n"
            html += f"<span class='stat'>NMI: {nmi}</span>\n"
            n_iso = len(comp.get('isoform_specific_clusters', []))
            if n_iso > 0:
                html += f"<span class='stat'>{n_iso} isoform-specific"
                html += f" cluster(s)</span>\n"
        html += "</div>\n"

    # Diversity
    div_file = out_dir / "isoform_diversity.tsv"
    if div_file.exists():
        div_df = pd.read_csv(div_file, sep='\t')
        html += "<div class='section'>\n<h3>Isoform Diversity</h3>\n"
        html += _histogram_html(
            div_df['diversity_index'].dropna().values,
            title='Isoform Diversity Index',
            xlabel='Shannon Entropy',
            div_id='diversity_hist')
        html += "</div>\n"

    return html


def _build_celltype_section(out_dir):
    """Build cell type annotation section."""
    ct_file = out_dir / "cluster_cell_types.tsv"
    if not ct_file.exists():
        return ""
    ct_df = pd.read_csv(ct_file, sep='\t')
    html = "<h2>Cell Type Annotation</h2>\n<div class='section'>\n"
    n_ann = int((ct_df['cell_type'] != 'Unknown').sum()) \
        if 'cell_type' in ct_df.columns else 0
    html += f"<p>{n_ann}/{len(ct_df)} clusters annotated.</p>\n"
    html += _table_html(ct_df)
    html += "</div>\n"
    return html


def _build_dtu_section(out_dir):
    """Build DTU section."""
    dtu_file = out_dir / "dtu_results.tsv"
    if not dtu_file.exists():
        return ""
    dtu_df = pd.read_csv(dtu_file, sep='\t')
    html = "<h2>Differential Transcript Usage</h2>\n"
    html += "<div class='section'>\n"

    sig = dtu_df[dtu_df['pvalue_adj'] < 0.05] \
        if 'pvalue_adj' in dtu_df.columns else pd.DataFrame()
    html += f"<span class='stat'>Tested: {len(dtu_df)} genes</span>\n"
    html += f"<span class='stat'>Significant: {len(sig)} "
    html += f"(FDR < 0.05)</span>\n"
    html += _table_html(sig.head(30))

    # Switching events
    sw_file = out_dir / "isoform_switching.tsv"
    if sw_file.exists():
        sw_df = pd.read_csv(sw_file, sep='\t')
        if len(sw_df) > 0:
            html += f"<h3>Isoform Switching Events ({len(sw_df)})</h3>\n"
            html += _table_html(sw_df.head(20))
    html += "</div>\n"
    return html


def _build_novel_section(out_dir):
    """Build novel isoform section."""
    cat_file = out_dir / "novel_isoform_catalog.tsv"
    if not cat_file.exists():
        return ""
    cat_df = pd.read_csv(cat_file, sep='\t')
    html = "<h2>Novel Isoform Discovery</h2>\n<div class='section'>\n"

    sum_file = out_dir / "novel_isoform_summary.json"
    if sum_file.exists():
        with open(sum_file) as fh:
            ns = json.load(fh)
        html += f"<span class='stat'>Novel isoforms: "
        html += f"{ns.get('n_novel_in_matrix', 0)}</span>\n"
        html += f"<span class='stat'>Cluster-enriched: "
        html += f"{ns.get('n_significant_enrichments', 0)}</span>\n"
        html += f"<span class='stat'>Cluster-specific: "
        html += f"{ns.get('n_cluster_specific_isoforms', 0)}</span>\n"
        cc = ns.get('class_code_distribution', {})
        for code, count in sorted(cc.items()):
            html += f"<span class='stat'>Class {code}: {count}</span>"

    html += "<h3>Top Novel Isoforms</h3>\n"
    html += _table_html(cat_df.head(30))
    html += "</div>\n"
    return html


def _build_trajectory_section(out_dir):
    """Build trajectory section."""
    sw_file = out_dir / "trajectory_switching.tsv"
    if not sw_file.exists():
        return ""
    sw_df = pd.read_csv(sw_file, sep='\t')
    html = "<h2>Isoform Trajectory</h2>\n<div class='section'>\n"
    html += f"<p>{len(sw_df)} isoform switching events along "
    html += f"pseudotime trajectory.</p>\n"
    html += _table_html(sw_df.head(30))
    html += "</div>\n"
    return html


def _build_ase_section(out_dir):
    """Build ASE section."""
    ase_file = out_dir / "ase_results.tsv"
    if not ase_file.exists():
        return ""
    ase_df = pd.read_csv(ase_file, sep='\t')
    html = "<h2>Allele-Specific Expression</h2>\n<div class='section'>\n"
    sig = ase_df[ase_df.get('pvalue_adj', 1) < 0.05] \
        if 'pvalue_adj' in ase_df.columns else pd.DataFrame()
    html += f"<span class='stat'>Variants tested: "
    html += f"{len(ase_df)}</span>\n"
    html += f"<span class='stat'>Significant: {len(sig)}</span>\n"
    html += _table_html(sig.head(30))
    html += "</div>\n"
    return html


def main(args):
    """Generate sciso HTML report."""
    logger = get_named_logger("Report")
    out_dir = Path(args.out_dir)

    logger.info(f"Generating report from {out_dir}")

    sections = ""
    sections += _build_clustering_section(out_dir)
    sections += _build_celltype_section(out_dir)
    sections += _build_dtu_section(out_dir)
    sections += _build_novel_section(out_dir)
    sections += _build_trajectory_section(out_dir)
    sections += _build_ase_section(out_dir)

    html = REPORT_TEMPLATE.format(sections=sections)

    output = Path(args.output)
    output.write_text(html)
    logger.info(f"Report written to {output}")
